export const CircleFood = [
  {
    name: "Salade Cesar",
    ingredient: "",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Salade Nicoise",
    ingredient: "",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Salad Chef",
    ingredient: "",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Pomme Frite",
    ingredient: "",
    price: "3",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Samoussa",
    ingredient: "",
    price: "7",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Chicken Tenders",
    ingredient: "",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Shawarma Poulet Sand",
    ingredient: "",
    price: "5",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Shawarma Viande Sand",
    ingredient: "",
    price: "5",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Shawarma Poulet Plat",
    ingredient: "",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Shawarma Viande Plat",
    ingredient: "",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "T Bone Steak",
    ingredient: "",
    price: "32",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Filet Poissons Pane",
    ingredient: "",
    price: "17",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Pizza Margarita",
    ingredient: "",
    price: "17",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Pizza Pepperoni",
    ingredient: "",
    price: "20",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Pizza Romeo",
    ingredient: "",
    price: "21",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Pizza Maison",
    ingredient: "",
    price: "19",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Plat Burger Le Palais",
    ingredient: "",
    price: "16.5",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Sand Burger Le Palais",
    ingredient: "",
    price: "8",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Plat Hamburger",
    ingredient: "",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Sand Hamburger",
    ingredient: "",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Plat Chicken Burger",
    ingredient: "",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Sand Chicken Burger",
    ingredient: "",
    price: "6.5",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Plat Escalope Panne",
    ingredient: "",
    price: "6.5",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
];

export const CircleDesserts = [
  {
    name: "Crepe Chocolat",
    ingredient: "",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "Gauffre",
    ingredient: "",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
];

export const ComingSoon = [
  {
    name: "",
    ingredient: "",
    price: "",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "",
    ingredient: "",
    price: "",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "",
    ingredient: "",
    price: "",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
  {
    name: "",
    ingredient: "",
    price: "",
    desc: "",
    image: "https://i.ibb.co/MydJbVW/l-image-est-en-construction.png",
  },
];
