// palais original
export const palaisMenuAmuseBouche = [
  {
    name: "Batonnet De Mozzarella",
    ingredient: "5 pièces mozzarella pané, sauce cocktail",
    price: "8",
    desc: "",
    image: "https://i.ibb.co/f8VFxjP/batonet-mozerella.jpg",
  },
  {
    name: "Fish Tender",
    ingredient: "5 pièces de poulet pané, sauce moutarde au miel",
    price: "9.5",
    desc: "",
    image: "",
  },
  {
    name: "Fish Finger",
    ingredient: "5 pièces de poisson pané, sauce tartare",
    price: "10",
    desc: "",
    image: "https://i.ibb.co/472NK3p/fish-fingers.jpg",
  },
  {
    name: "Crevettes Butterfly",
    ingredient: "6 pièces de crevettes pané, sauce tartare",
    price: "11.5",
    desc: "",
    image: "",
  },
  {
    name: "Ailes de Buffalo Parmeson",
    ingredient:
      "10 pièces d'ailes de poulet pané, sauce buffalo, fromage parmeson",
    price: "10.5",
    desc: "",
    image: "",
  },
  {
    name: "Rouleaux aux Crevettes",
    ingredient:
      "5 pièces de pate filo farcie de légumes et petites crevettes, sauce cocktail",
    price: "12.5",
    desc: "",
    image: "",
  },
  {
    name: "Wedges Potatos",
    ingredient: "pomme de terre, crème aigre doux, bbq sauce, sauce cocktail",
    price: "7.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Nuggets de Poulet",
    ingredient: "8 pièces blanc de poulet pané, sauce cocktail",
    price: "7.5",
    desc: "",
    image: "",
  },
  {
    name: "Calamars du Pêcheur",
    ingredient: "8 pièces calamar mariné, sauce tartar",
    price: "11.5",
    desc: "",
    image: "",
  },
  {
    name: "Nachos",
    ingredient:
      "nachos, fromage, olive noire, jalapeno, sauce guacamole, crème aigre",
    price: "8.5",
    desc: "",
    image: "",
  },
  {
    name: "Pommes Frites",
    ingredient: "",
    price: "3.00",
    desc: "",
    image: "https://i.ibb.co/xMpbywb/fries-1.jpg",
  },
  {
    name: "Tempura de Crevettes",
    ingredient: "5 pièces de crevettes, chilli sauce",
    price: "12.5",
    desc: "",
    image: "",
  },
  {
    name: "Crispy au Poulet",
    ingredient: "5 pièces de ppoulet, sauce cocktail",
    price: "",
    desc: "",
    image: "",
  },
];

export const palaisSalades = [
  {
    name: "Salade vague du sud",
    ingredient: "iceberg, tomate cerise, fromage feta, noix, essence citronnée",
    price: "10",
    desc: "",
    image: "",
  },
  {
    name: "Salade Méchwia (légumes grillés)",
    ingredient: "Tomate, oignon, poivron, ail, oeuf, thon, olive",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Tartare de Saumon",
    ingredient:
      "saumon frais, oignons câpre, persil, citron, avocat, huile d'olive",
    price: "18",
    desc: "",
    image: "",
  },
  {
    name: "Cocktail de Crevettes",
    ingredient:
      "crevette, iceberg, tomate cerise, avocat, pâte d'arachide, sauce cocktail",
    price: "18",
    desc: "",
    image: "",
  },
  {
    name: "Salade César",
    ingredient: "Iceberg, crouton, poitrine de poulet, parmesan, sauce césar",
    price: "13.00",
    desc: "",
    image: "https://i.ibb.co/d0jZ8t4/salad1.jpg",
  },
  {
    name: "Salade Crabe",
    ingredient: "Iceberg, crabe, mais, sauce citron",
    price: "17",
    desc: "",
    image: "",
  },
  {
    name: "Salade Niçoise",
    ingredient:
      "Iceberg, tomate, thon, œufs, haricot vert, olives, sauce citron, concombre",
    price: "14.00",
    desc: "",
    image: "https://i.ibb.co/StshT45/salad2.jpg",
  },
  {
    name: "Salade Le Palais",
    ingredient:
      "Quinoa, raisins secs, mangues, menthe, tomates cerise, fromages feta, sauce citron",
    price: "13.00",
    desc: "",
    image: "https://i.ibb.co/pvNmxSk/salad3.jpg",
  },
  {
    name: "Salade Grecque",
    ingredient:
      "Iceberg, concombres, olives noire, fromage feta, tomate, origan, sauce citron",
    price: "12.00",
    desc: "",
    image: "https://i.ibb.co/njmbCzf/salad4.jpg",
  },
  {
    name: "Coussinet de Chèvre",
    ingredient:
      "Fromage de chèvre, noisettes, olive, salade iceberg, sauce balsamique",
    price: "15",
    desc: "",
    image: "",
  },
  {
    name: "Poêlee de Saint Jacques",
    ingredient: "Escalope de saint jacques, crème fraiche, citron",
    price: "12.5",
    desc: "",
    image: "",
  },
];

export const palaisPatesEtRisottos = [
  {
    name: "Penne au saumon",
    ingredient:
      "saumon frais et gambas carpeau de parmesan, sauce crème safranée, basilic frais",
    price: "20",
    desc: "",
    image: "",
  },
  {
    name: "Spaghetti aux Crevettes",
    ingredient:
      "Spagetti, crevettes, sauce tomate, crème fraiche, fromage parmesan",
    price: "29",
    desc: "",
    image: "",
  },
  {
    name: "Pate aux Quatre Fromages",
    ingredient: "pates penne, crème fraiche, mélange de quatre fromages",
    price: "15.5",
    desc: "",
    image: "",
  },
  {
    name: "Risotto aux Crevettes",
    ingredient: "Risotto, crevette, crème fraiche, fromage parmesan",
    price: "20",
    desc: "",
    image: "",
  },
  {
    name: "Risotto aux Champignons",
    ingredient: "Risotto, champignons, crème fraiche, fromage parmesan",
    price: "18",
    desc: "",
    image: "",
  },
  {
    name: "Fettucini Alfredo",
    ingredient:
      "pate fetuccini, crème fraiche, poitrine de poulet, champignons, parmesan",
    price: "13",
    desc: "",
    image: "",
  },
  {
    name: "Spagetti Bolognaise",
    ingredient: "Spagetti, viande hanchée, sauce tomate, fromage parmesan",
    price: "13",
    desc: "",
    image: "",
  },
];

export const palaisPizza = [
  {
    name: "Pizza Maison",
    ingredient: "Sauce tomate, jambon, olive, champignon, fromage mozerella",
    price1: "13",
    price2: "18.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza Peppéroni",
    ingredient: "Sauce tomate, saucisse piquante, fromage mozerella",
    price1: "14.5",
    price2: "19.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza Quatre fromages",
    ingredient: "sauce tomate, roquefort, mozerella, emmental, parmesan",
    price1: "15",
    price2: "20.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza Fruits de Mer",
    ingredient: "sauce tomate, mélange de fruits de mer, fromage mozerella",
    price1: "16.5",
    price2: "22",
    desc: "",
    image: "",
  },
  {
    name: "Pizza 4 saisons",
    ingredient: "Sauce tomate, artichaut, champignon, jambon, tomate",
    price1: "14",
    price2: "19.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza au Poulet Fumé et Pistou",
    ingredient:
      "sauce blanc, dés poulet fumé, mais, poivrons, pistou, fromage mozerella",
    price1: "14.5",
    price2: "19.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza dinde",
    ingredient: "sauce tomate, dinde fumé, olive, champignon, mais, poivron",
    price1: "14",
    price2: "19.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza au Thon",
    ingredient: "sauce tomate, thon, olives, mais, povron",
    price1: "14",
    price2: "19.5",
    desc: "",
    image: "",
  },
  {
    name: "Pizza Soujouk",
    ingredient: "sauce tomate, soujouk, mais, poivron, fromage mozerella",
    price1: "14",
    price2: "195",
    desc: "",
    image: "",
  },
];

export const palaisSandwiches = [
  {
    name: "Croque Monsieur",
    ingredient: "Pain de mie, dinde fumé, fromage mozerella, origan",
    price: "7",
    desc: "",
    image: "",
  },
  {
    name: "Club Rosto",
    ingredient:
      "pain de mie, viande rosto, fromage mozerella, laitue, tomate, cornichon, moutarde à l'ancienne, sauce mayonnaise",
    price: "7.5",
    desc: "",
    image: "",
  },
  {
    name: "Club Sandwich",
    ingredient:
      "pain de mie, poitrine de poulet, fromage mozarella, tomate, oeufs, sauce pesto",
    price: "8.5",
    desc: "",
    image: "",
  },
  {
    name: "Fajitas",
    ingredient:
      "Poitrine de poulet, poivron vert, oignon, champignons de Paris, maïs, soya sauce, sauce guacamole, laitue, mozzarella",
    price: "7.00",
    desc: "",
    image: "https://i.ibb.co/xmPVgrN/chicken-fajita-sandwich.jpg",
  },
  {
    name: "Philadelphia",
    ingredient:
      "viande, poivron vert, oignon, champignon, maïs, soya sauce, mozzarella, sauce cocktail",
    price: "7.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Francisco",
    ingredient:
      "Poulet grillé, fromage mozzarella, maïs, cornichon, laitue, sauce mayonnaise",
    price: "7.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Roast Beef",
    ingredient:
      "viande, rosto, menthe, tomates, iceberg, mayonnaise, moutarde, cornichons",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Halloumi",
    ingredient: "Pain baguette, fromage halloumi, concombre, sauce pistou",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Oriental",
    ingredient:
      "Pain baguette, labneh, concombre, menthe, olives vertes, huile d'olive",
    price: "4",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Frites",
    ingredient: "Frites, choux mayonnaise, ketchup, cornichons",
    price: "3.50",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Sandwich Crevettes Panées",
    ingredient:
      "Crevettes panées, iceberg, cornichon, tomates, sauce cocktail et tartare",
    price: "8",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Quésadillas",
    ingredient:
      "Poitrine de poulet, oignons, poivrons, fromage mozzarella, fromage cheddar, sauce guacamole, pain tortillas, jalopenos et olive",
    price: "8.50",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Sandwich Twister Au Poulet",
    ingredient:
      "Poitrine de poulet mariné, iceberg, cornichons, ketshup, mayonnaise, pain tortillas, fromage cheddar, jalapenos",
    price: "6.50",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Zinger Chicken",
    ingredient:
      "Poulet pané, piment, laitue, cornichon, sauce mayonnaise à l'ail et cheddar",
    price: "7.5",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Ras Asfour",
    ingredient: "Emincée de viande, choux mayonaise, pomme frites",
    price: "6",
    desc: "",
    image: "",
  },
  {
    name: "Sandwich Falafel",
    ingredient: "Tomate, cornichons, persil, sauce sésame",
    price: "6.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
];

export const palaisBurgers = [
  {
    name: "Hamburger Sand",
    ingredient:
      "viande hanchée, choux mayonnaise, laitue, moutarde, ketchup, tomate, oignon grillé",
    price: "6.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Hamburger Plat",
    ingredient:
      "2 viande hanchée, choux mayonnaise, laitue, moutarde, ketchup, tomate, oignon grillé, fries",
    price1: "13.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Cheese Burger Sand",
    ingredient:
      "viande hanchée, choux mayonnaise, laitue, moutarde, ketchup, tomate, oignon grillé, fromage cheddar",
    price: "7.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Cheese Burger Plat",
    ingredient:
      "2 viande hanchée, choux mayonnaise, laitue, moutarde, ketchup, tomate, oignon grillé, fromage cheddar, fries",
    price: "15.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger au Poulet Sand",
    ingredient:
      "Poulet grillé, laitue, tomate, cornichon, sauce mayonnaise à l'ail",
    price: "8.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger au Poulet Plat",
    ingredient:
      "2 Poulet grillé, laitue, tomate, cornichon, sauce mayonnaise à l'ail, fries",
    price: "14.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger Le Palais Sand",
    ingredient:
      "viande hanchée, fromage mozerella pané, laitue, tomate, cornichon, sauce cocktail",
    price: "8.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger Le Palais Plat",
    ingredient:
      "2 viande hanchée, fromage mozerella pané, laitue, tomate, cornichon, sauce cocktail, fries",
    price: "16.50",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "American Burger Sand",
    ingredient:
      "viande hanchée marinée grillée, laitue, oignon frais, tomate, sauce HP, ketchup",
    price: "9.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "American Burger Plat",
    ingredient:
      "2 viande hanchée marinée grillée, laitue, oignon frais, tomate, sauce HP, ketchup, fries",
    price: "17.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger Au Poisson Sand",
    ingredient: "Poisson pané, laitue, tomate, sauce tartare",
    price: "7.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Burger Au Poisson Plat",
    ingredient:
      "2 Poisson pané, laitue, tomate, sauce tartare, choux mayonaise, frites",
    price: "16.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Zinger Burger Sand",
    ingredient:
      "Poulet pané piquant, laitue, tomate, cornichon, sauce cocktail",
    price: "8.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Zinger Burger Plat",
    ingredient:
      "2 Poulet pané piquant, laitue, tomate, cornichon, sauce cocktail, frites",
    price: "16.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
];

export const palaisMezzesFroids = [
  {
    name: "Tabbouleh",
    ingredient:
      "Persil, oignon, tomate, blé concasse, jus de citron, huile d olive",
    price: "8.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Fattouch",
    ingredient:
      "Laitue, tomate, persil, concombre, oignon, radis, jus de citron, huile d olive, épice sumac, pain arabe grillé",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Hommos (Nature)",
    ingredient: "Purée de pois chiches, crème de sésame, jus de citron",
    price: "6.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Moutabal",
    ingredient: "Purée d aubergine, crème de sésame, jus de citron",
    price: "6.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Chancklich",
    ingredient: "Fromage feta épicé traditionnel, tomate, oignon",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Feuilles de Vigne",
    ingredient: "Feuille de vigne farcie au légumes et au riz",
    price: "7.5",
    desc: "",
    image: "",
  },

  {
    name: "Kebbeh Nayeh",
    ingredient: "viande de chèvre crue, blé concassé",
    price: "13",
    desc: "",
    image: "",
  },

  {
    name: "Hommos Beiruty",
    ingredient:
      "Purée de pois chiches, crème de sésame, citron, cornichon, persil",
    price: "6.5",
    desc: "",
    image: "",
  },

  {
    name: "Hommos Piquant",
    ingredient: "Purée de Pois chiches au piment rouge",
    price: "7",
    desc: "",
    image: "",
  },
];
export const palaisMezzesChauds = [
  {
    name: "Ailes De Poulet",
    ingredient: "Ailes de poulet à la provençale, persil, ail, oignon",
    price: "6.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Makanik",
    ingredient: "Saucisse libanaise poêlées, sauce citron",
    price: "10.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Soujouk",
    ingredient: "Saucisse libanaise poêlées, sauce piquante",
    price: "10.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Pomme de terre à la Provençale",
    ingredient: "Dés de pomme de terre à la sauce provençale piquante",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Viande Ras Asfour",
    ingredient: "petite dés de viande cuite à la mélasse de grenadine",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Hommos viande",
    ingredient: "viande poêlée sur un lit de hommos nature",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Hommos Chawarma",
    ingredient: "chawarma viande sur un lit de hommos nature",
    price: "8",
    desc: "",
    image: "",
  },
  {
    name: "Falafel",
    ingredient:
      "Mélange légumineux épicé, sauce sésame, légume frais, cornichon",
    price: "10.5",
    desc: "",
    image: "",
  },
  {
    name: "Briks au Thon",
    ingredient: "Feuille de brick, pomme de terre, persil, thon, oeuf",
    price: "7",
    desc: "",
    image: "",
  },
  {
    name: "Ojja aux Crevettes",
    ingredient:
      "Sauce tomate à la tunisienne, crevette, poivron, tomate, ail, oeuf",
    price: "13",
    desc: "",
    image: "",
  },
  {
    name: "Kebbeh Nature",
    ingredient: "4 pièces boulette farcie de viande et pignon",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Rekakat au fromage",
    ingredient: "4 pièces de pâte feuilletée aux fromages",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Samossa viande",
    ingredient: "4 pièces de pâte farcie à la viande hachée",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Fatayer Epinard",
    ingredient: "4 pièces de pâte farcie aux épinards marinés",
    price: "6.5",
    desc: "",
    image: "",
  },
];

export const palaisShawarma = [
  {
    name: "Shawarma Viande Sand",
    ingredient: "viande marinée et grillée, Salade biwaz, tomate, sauce sésame",
    price: "4.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Viande Plat",
    ingredient: "viande marinée et grillée, Salade biwaz, tomate, sauce sésame",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Poulet Sand",
    ingredient: "Poulet mariné et grillé, cornichon, ail, frites",
    price: "4.5",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Poulet Plat",
    ingredient: "Poulet mariné et grillé, cornichon, ail, frites",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Saj Sand",
    ingredient: "Viande ou poulet, pain saj libanais traditionel",
    price: "7.00",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Saj Plat",
    ingredient: "Viande ou poulet, pain saj libanais traditionel, frite",
    price: "15",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Le Palais Sand",
    ingredient:
      "Shawarma viande marinée avec sauce grenadine, salade biwaz tomate, sauce sésame",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Shawarma Le Palais Plat",
    ingredient:
      "Shawarma viande marinée avec sauce grenadine, salade biwaz tomate, sauce sésame",
    price: "15",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
];

export const palaisGrillades = [
  {
    name: "Arayes Kafta",
    ingredient: "pain libanais grillé farci de kafta",
    price: "8.5",
    desc: "",
    image: "",
  },
  {
    name: "Taouk Sandwich",
    ingredient:
      "Brochettes de poulet marinée, sauce à l’ail, cornichon, frites",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Taouk Plat",
    ingredient:
      "Brochettes de poulet marinée, sauce à l’ail, cornichon, frites",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kabab Ourfali Sandwich",
    ingredient: "Viande émincée grillée pimentée, aubergine, tomate, oignon",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kabab Ourfali Plat",
    ingredient:
      "Viande émincée grillée pimentée, aubergine, tomate, oignon, frite",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kafta Sandwich",
    ingredient:
      "Viande émincée et moulue avec persil et oignon grillé servie avec divers condiments",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kafta Plat",
    ingredient:
      "Viande émincée et moulue avec persil et oignon grillé servie avec divers condiments, frites",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kabab Kish Kash Sandwich",
    ingredient:
      "viande émincée et moulue avec pimentée servie avec divers condiments",
    price: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Kabab Kish Kash Plat",
    ingredient:
      "viande émincée et moulue avec pimentée servie avec divers condiments, fries",
    price: "15",
    desc: "",
    image: "",
  },
  {
    name: "Kabab Halabi Sandwich",
    ingredient:
      "Viande émincée et moulue avec sauce piment, servie avec divers condiments",
    price: "6",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Kabab Halabi Plat",
    ingredient:
      "Viande émincée et moulue avec sauce piment, servie avec divers condiments, frite",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Brochettes De Viande Sand",
    ingredient:
      "Brochettes de viande marinée et grillée, servie avec divers condiments",
    price: "7",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Brochettes De Viande Plat",
    ingredient:
      "2 Brochettes kafta, 1 brochette viande, 1 brochette taouk, frittes, hommos, sauce a l’ail, frite",
    price: "14",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Grillade Mixte",
    ingredient:
      "2 Brochettes kafta, 1 brochette viande, 1 brochette taouk, frites",
    price: "15",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Poulet Entier Désossé Grillé",
    ingredient:
      "Poulet mariné et grillé, servie avec cornichon sauce à l’ail et frites",
    price: "21",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
  {
    name: "Demi Poulet Entier Désossé Grillé",
    ingredient:
      "Poulet mariné et grillé, servie avec cornichon sauce à l’ail et frites",
    price: "13",
    desc: "",
    image: "https://i.ibb.co/Tr1mmZx/wedges-potato.jpg",
  },
];

export const palaisPlats = [
  {
    name: "Sizzling Fajitas",
    ingredient:
      "Poulet mariné, légumes poêlés, servis sur une plaque chaude, guacamole, crème aigre, pain tortilla",
    price: "22",
    desc: "",
    image: "",
  },
  {
    name: "Poulet Mexicain",
    ingredient:
      "Poitrine de poulet, oignons, poivron, haricot rouge, jalopenos, concassée de tomate, riz, mais",
    price: "24",
    desc: "",
    image: "",
  },
  {
    name: "Poulet à la congolaise",
    ingredient: "Poulet grillé, sauce tomate, banane Plantin",
    price: "15",
    desc: "",
    image: "",
  },
  {
    name: "Escalope Pané",
    ingredient:
      "Escalope de poulet, frite, choux, mayonnaise, sauté de légumes",
    price: "20",
    desc: "",
    image: "",
  },
  {
    name: "Cordon Bleu au poulet",
    ingredient:
      "Poulet farci, fromage mozzarella, jambon de dinde, légumes sautés, frites, sauce moutarde",
    price: "26",
    desc: "",
    image: "",
  },
  {
    name: "Sizzling Philadelphia",
    ingredient:
      "Viande marinée, légumes poêlés, servis sur une plaque chaude, sauce guacamole, crème aigre, pain tortilla",
    price: "25",
    desc: "",
    image: "",
  },
  {
    name: "Couscous à la Viande",
    ingredient:
      "Semoule, sauce épicée, viande, oignon, courgette, carotte, courge rouge",
    price: "25",
    desc: "",
    image: "",
  },
  {
    name: "Filet Mignon",
    ingredient:
      "Filet de boeuf grillé, purée d'avocat, légumes sautés, sauce champignon ou sauce poivre",
    price: "29",
    desc: "",
    image: "",
  },
  {
    name: "T _ Bone Steak",
    ingredient: "T-Bone Steak grillé, légumes sautés, frites, sauce au choix",
    price: "29",
    desc: "",
    image: "",
  },
  {
    name: "Côtelettes d’agneaux",
    ingredient:
      "Côtelettes d’agneaux, julienne de légumes, wedges potato, mousse de betterave",
    price: "30",
    desc: "",
    image: "",
  },
  {
    name: "Poisson du Jour",
    ingredient: "Poisson au four + Banane plantain + Sauce provençale",
    price: "24",
    desc: "",
    image: "",
  },
  {
    name: "Filet de Capitaine",
    ingredient:
      "Filet de capitaine grillé, pomme purée, légumes sautés, ratatouille, sauce crème à l’aneth",
    price: "22",
    desc: "",
    image: "",
  },
  {
    name: "Saumon à la sauce Soja",
    ingredient:
      "Saumon frais, risotto, sauce soja, artichaut, mesclun de légume",
    price: "29",
    desc: "",
    image: "",
  },
  {
    name: "Crevettes à la thaïlandaise",
    ingredient:
      "Crevettes Royales, sauce curry au lait de coco, riz au coriandre",
    price: "28",
    desc: "",
    image: "",
  },
  {
    name: "Cossas Royales",
    ingredient:
      "Cossas Royales, beurre pimenté à l'ail, accompagnement riz ou banane Plantin",
    price: "29",
    desc: "",
    image: "",
  },
];

export const palaisGarnitureExtra = [
  {
    name: "Riz",
    ingredient: "",
    price: "4",
    desc: "",
    image: "",
  },
  {
    name: "Banane Plantain (makemba)",
    ingredient: "",
    price: "5",
    desc: "",
    image: "",
  },
  {
    name: "Purée de la Pomme de Terre",
    ingredient: "",
    price: "5",
    desc: "",
    image: "",
  },
  {
    name: "Pomme de Terre Sautée",
    ingredient: "",
    price: "3",
    desc: "",
    image: "",
  },
  {
    name: "Légumes Sautés",
    ingredient: "",
    price: "3",
    desc: "",
    image: "",
  },
  {
    name: "Assiette de Légumes",
    ingredient: "",
    price: "6",
    desc: "",
    image: "",
  },
  {
    name: "Assiette de Cornichons",
    ingredient: "",
    price: "3",
    desc: "",
    image: "",
  },
  {
    name: "Sauce Ail Grande",
    ingredient: "",
    price: "7",
    desc: "",
    image: "",
  },
  {
    name: "Sauce Ail Petite",
    ingredient: "",
    price: "2",
    desc: "",
    image: "",
  },
];

export const palaisManakishEtKaak = [
  {
    name: "Manakish Fromage",
    ingredient: "Fromage akkawi",
    price: "3.5",
    price2: "5",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Zaatar",
    ingredient: "thym, sésame, huile",
    price: "2.5",
    price2: "3.5",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Turkish",
    ingredient: "Fromage, tomate, oignon, sésame, sauce pimentée",
    price: "4",
    price2: "6.5",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Viande",
    ingredient: "viande epicée, tomate, oignon",
    price: "3",
    price2: "4",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Labneh",
    ingredient: "labneh, tomate, concombre, olive",
    price: "2.5",
    price2: "4",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Cocktail Fromage / Zaatar",
    ingredient: "fromage, zaatar",
    price: "3",
    price2: "4.5",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Epinard",
    ingredient: "épinard, tomate, oignon, sauce grenadine",
    price: "2.5",
    price2: "4",
    desc: "",
    image: "",
  },
  {
    name: "Manakish Soujouk Fromage",
    ingredient: "fromage, soujouk",
    price: "4",
    price2: "4",
    desc: "",
    image: "",
  },
  {
    name: "Kaake Fromage",
    ingredient: "fromage akkawi ou halloumi",
    price: "7.5",
    desc: "",
    image: "",
  },
  {
    name: "Kaake Zaatar / Fromage",
    ingredient: "",
    price: "7.5",
    desc: "",
    image: "",
  },
  {
    name: "Kaake Zaatar",
    ingredient: "",
    price: "4",
    desc: "",
    image: "",
  },
];

export const palaisDesserts = [
  {
    name: "Tiramisu",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Cheese Cake",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Crèpe au Chocolat",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Fondant au Chocolat",
    ingredient: "",
    price: "10",
    desc: "",
    image: "",
  },
  {
    name: "Nougat Glacé",
    ingredient: "",
    price: "10",
    desc: "",
    image: "",
  },
  {
    name: "Mouhalabiyé",
    ingredient: "",
    price: "8",
    desc: "",
    image: "",
  },
  {
    name: "Banana Split",
    ingredient: "",
    price: "8",
    desc: "",
    image: "",
  },
  {
    name: "Ousmaliyé",
    ingredient: "",
    price: "10",
    desc: "",
    image: "",
  },
  {
    name: "Aish El Saraya",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Knafeh",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Halawet El Jibn",
    ingredient: "",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Mariage de Trois Glaces",
    ingredient: "",
    price: "10",
    desc: "",
    image: "",
  },
];

// SUSHI
export const palaisSushiNegiri = [
  {
    name: "Ebi Shrimp",
    ingredient: "Crevettes Japonaises, Riz",
    pieces: "2 peices",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/5B5Dm9P/Ebi-Shrimp.jpg",
  },
  {
    name: "Green Masago",
    ingredient: "Oeufs de Poissons, Nori, Riz",
    pieces: "2 peices",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Hokkigai",
    ingredient: "Coquillages de Hockey, Riz",
    pieces: "2 peices",
    price: "9",
    desc: "",
    image: "",
  },
  {
    name: "Kani Stick",
    ingredient: "Bâtonnets De Kani Crabe, Nori, Riz",
    pieces: "2 peices",
    price: "10",
    desc: "",
    image: "",
  },
  {
    name: "Salmon",
    ingredient: "Saumon, Riz",
    pieces: "2 peices",
    price: "9.5",
    desc: "",
    image: "",
  },
  {
    name: "Scallop",
    ingredient: "Saint-Jacques, Nori, Riz",
    pieces: "2 peices",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Tuna",
    ingredient: "Thon, Riz",
    pieces: "2 peices",
    price: "9.5",
    desc: "",
    image: "",
  },
  {
    name: "Unagi Eel",
    ingredient: "Anguille, Nori, Riz",
    pieces: "2 peices",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Viya Crab",
    ingredient: "Viya Crabe, Tobiko, Mayonnaise Japonaise, Nori, Riz",
    pieces: "2 peices",
    price: "12",
    desc: "",
    image: "",
  },
  {
    name: "Yellowtail",
    ingredient: "Sériole, Riz",
    pieces: "2 peices",
    price: "12",
    desc: "",
    image: "",
  },
];
export const palaisSushiEntreesEtSalades = [
  {
    name: "Edamame",
    ingredient: "Hricots Verts Japonais",
    pieces: "",
    price: "9",
    desc: "",
    image: "https://i.ibb.co/z8fHRnW/edamam.jpg",
  },
  {
    name: "Green Vegetables (V)",
    ingredient:
      "Edamame, Avocat, Iceberg, Lolo Rosso, Tomates Cerises, Sauces Aux Pomme",
    pieces: "",
    price: "13",
    desc: "",
    image: "",
  },
  {
    name: "Salade Le Palais",
    ingredient:
      "Saumon Frais, Avocat, Concombre, Iceberg, Lolo Rosso, Poivron Vert, Tomates Cerises, Sauce Aux Herbes",
    pieces: "",
    price: "17",
    desc: "",
    image: "",
  },
  {
    name: "Ocean Prawns",
    ingredient:
      "Crevettes Japonaises, Avocat, Iceberg, Tomate Cerises, Lolo Rosso, Sauce Vinaigrette Au Citron Epicée",
    pieces: "",
    price: "17",
    desc: "",
    image: "",
  },
  {
    name: "Salade Kani Kama",
    ingredient:
      "Kani Crabe, Concombre, Iceberg, Lolo Rosso, Tobiko, Croquant Mayonnaise Japonaise",
    pieces: "",
    price: "23",
    desc: "",
    image: "",
  },
  {
    name: "Okinawa",
    ingredient:
      "Kani Crabe, Saumon Frais, Iceberg, Concombre, Epis de Mais, Oeufs de Capelan, Sauce Aux Herbes",
    pieces: "",
    price: "26",
    desc: "",
    image: "",
  },
  {
    name: "Salade Majestic Crunchy (Salmon Or Tuna)",
    ingredient:
      "Saumon ou Thon Frais, Iceberg Tobiko, Croquant, Wasabi, Mayonnaise Japonaise, Sauce de soja",
    pieces: "",
    price: "26.12",
    desc: "",
    image: "",
  },
];
export const palaisSushiMakiRolls = [
  {
    name: "Avocado (V)",
    ingredient: "Avocat, Nori, Riz",
    pieces: "3 pieces",
    price: "8",
    pieces2: "6 pieces",
    price2: "14",
    desc: "",
    image: "",
  },
  {
    name: "Crispy Salmon Skin",
    ingredient:
      "Kani Crabe, Peau de saumon frit, Mayonnnaise Japonaise Epicée, Nori, Riz",
    pieces: "3 pieces",
    price: "7",
    pieces2: "6 pieces",
    price2: "12",
    desc: "",
    image: "https://i.ibb.co/d4dSqYB/download-5.jpg",
  },
  {
    name: "Cucumbrer (V)",
    ingredient: "Concombre, Nori, Riz",
    pieces: "3 pieces",
    price: "6",
    pieces2: "6 pieces",
    price2: "10",
    desc: "",
    image: "",
  },
  {
    name: "Kani Crab",
    ingredient: "Kani Crabe, Nori, Riz",
    pieces: "3 pieces",
    price: "7.5",
    pieces2: "6 pieces",
    price2: "13",
    desc: "",
    image: "",
  },
  {
    name: "Negi Salmon",
    ingredient: "Saumon, Oignon Vert, Nori, Riz",
    pieces: "3 pieces",
    price: "9",
    pieces2: "6 pieces",
    price2: "16",
    desc: "",
    image: "",
  },
  {
    name: "Salmon",
    ingredient: "Saumon, Nori, Riz",
    pieces: "3 pieces",
    price: "8.5",
    pieces2: "6 pieces",
    price2: "15",
    desc: "",
    image: "",
  },
  {
    name: "Sea Food",
    ingredient:
      "Saumon, Crevettes, Saint-Jacques, Thon, Tobiko, Oignon Vert, Nori, Riz",
    pieces: "3 pieces",
    price: "10",
    pieces2: "6 pieces",
    price2: "18",
    desc: "",
    image: "",
  },
  {
    name: "Shrimp",
    ingredient: "Crevettes, Nori, Riz",
    pieces: "3 pieces",
    price: "8.5",
    pieces2: "6 pieces",
    price2: "15",
    desc: "",
    image: "",
  },
  {
    name: "Tuna & Avocado",
    ingredient: "Thon, Avodat, Nori, Riz",
    pieces: "3 pieces",
    price: "8.5",
    pieces2: "6 pieces",
    price2: "15",
    desc: "",
    image: "",
  },
  {
    name: "Unagi Kyu",
    ingredient: "Anguille, Concombre, Nori, Riz",
    pieces: "3 pieces",
    price: "9.5",
    pieces2: "6 pieces",
    price2: "17",
    desc: "",
    image: "",
  },
  {
    name: "Yasai (V)",
    ingredient: "Carotte, Concombre, Iceberg, Avocat, Poivron, Nori, Riz",
    pieces: "3 pieces",
    price: "6",
    pieces2: "6 pieces",
    price2: "10",
    desc: "",
    image: "",
  },
];
export const palaisSushiLePalaisRolls = [
  {
    name: "Fantastic",
    ingredient: "Anguile, Tobiko, Avocat, Concombre, Nori, Riz",
    pieces: "4 pieces",
    price: "12.5",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "https://i.ibb.co/0YtRNQM/fantastic.jpg",
  },
  {
    name: "Hokkaido Crunchy Shrimp",
    ingredient:
      "Thon, Avocat, Crevettes Tempura, Tobiko, Croquant, Mayonnaise Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
  {
    name: "Hokkigai Roll",
    ingredient:
      "Coquillages De Hockey, Kani Crabe, Avocat, Tobiko, Oeufs de Capelan, Nori, Riz",
    pieces: "4 pieces",
    price: "11",
    pieces1: "8 pieces",
    price1: "20",
    desc: "",
    image: "",
  },
  {
    name: "Italian Roll",
    ingredient: "Crevettes, Dinde, Mozzarella, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
  {
    name: "Lotus",
    ingredient: "Saumon Frais, Avocat, Tobik Fromage Philadelphia, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
  {
    name: "Osaka Grilled Salmon",
    ingredient: "Saumon Grillé, Kani Crabe, Sauce teriyaki, Nori, Riz",
    pieces: "4 pieces",
    price: "12.5",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "",
  },
  {
    name: "Philadelphia Tuna",
    ingredient: "Thon, Avocat, Kano Crabe, Fromage Philadelphia, Nori, Riz",
    pieces: "4 pieces",
    price: "11.5",
    pieces1: "8 pieces",
    price1: "21",
    desc: "",
    image: "",
  },
  {
    name: "Philly",
    ingredient:
      "Saumon Frais, Concombre, Fromage Philadelphia, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
  {
    name: "Rainbow",
    ingredient:
      "Thon et Saumon Frais, Kani Crabe, Concombre, Mayonnaise Japonaise, Nori, Riz",
    pieces: "4 pieces",
    price: "9.5",
    pieces1: "8 pieces",
    price1: "17",
    desc: "",
    image: "",
  },
  {
    name: "Rock'n Rolls",
    ingredient: "Saumon Frais, Avocat, Mayonnaise Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "9.5",
    pieces1: "8 pieces",
    price1: "17",
    desc: "",
    image: "",
  },
  {
    name: "Royal Salmon",
    ingredient:
      "Saumon Frais, Mangue, Crevettes, Tempura, Oeufs de Capelan, Nori, Riz",
    pieces: "4 pieces",
    price: "11.5",
    pieces1: "8 pieces",
    price1: "21",
    desc: "",
    image: "",
  },
  {
    name: "Tiffany",
    ingredient: "Sériole Frais, Kani Crabe, Saumon Frais, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "13.5",
    pieces1: "8 pieces",
    price1: "25",
    desc: "",
    image: "",
  },
  {
    name: "Kaizen",
    ingredient: "Thon, Saint-Jacques, Kani Crabe, Avocat, Concombre, Nori, Riz",
    pieces: "4 pieces",
    price: "13.5",
    pieces1: "8 pieces",
    price1: "25",
    desc: "",
    image: "",
  },
  {
    name: "Saisaki",
    ingredient: "Anguile, Kani Crabe, Avocat, Graines de Sésame, Nori, Riz",
    pieces: "4 pieces",
    price: "13",
    pieces1: "8 pieces",
    price1: "24",
    desc: "",
    image: "",
  },
  {
    name: "Atlantic Roll",
    ingredient:
      "Crevettes Jaunes, Crabe, Saumon Frais, Avocat, Algue, Nori, Riz",
    pieces: "4 pieces",
    price: "13",
    pieces1: "8 pieces",
    price1: "24",
    desc: "",
    image: "",
  },
  {
    name: "California",
    ingredient:
      "Kani Crabe, Tobiko, Avocat, Concombre, Mayonnaise Japonaise, Nori, Riz",
    pieces: "4 pieces",
    price: "9",
    pieces1: "8 pieces",
    price1: "16",
    desc: "",
    image: "",
  },
  {
    name: "Caterpillar",
    ingredient: "Anguille, Avocat, Concombre, Nori, Riz",
    pieces: "4 pieces",
    price: "10",
    pieces1: "8 pieces",
    price1: "16",
    desc: "",
    image: "",
  },
  {
    name: "Chugoku Spicy Crab & Shrimp",
    ingredient:
      "Kani Crabe, Thon, poudre de Chilli, Crevettes Tempura, Mayonnaise, Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "13.5",
    pieces1: "8 pieces",
    price1: "25",
    desc: "",
    image: "",
  },
  {
    name: "Crunchy Crazy",
    ingredient: "Viya Crabe, Tobiko, Avocat, Concombre, Croquant, Nori, Riz",
    pieces: "4 pieces",
    price: "12.5",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "",
  },
  {
    name: "Dragon",
    ingredient: "Thon Epicé, Concombre, Croquant, Poudre de chili, Nori, Riz",
    pieces: "4 pieces",
    price: "9.5",
    pieces1: "8 pieces",
    price1: "17",
    desc: "",
    image: "",
  },
  {
    name: "Dynamite Roll",
    ingredient: "Saumon Frais, Avocat, Pili-Pili, Oeufs de Capelan, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
];
export const palaisSushiSashimi = [
  {
    name: "Ebi Shrimp",
    ingredient: "Crevettes Japonaises",
    pieces: "4 pieces",
    price: "11",
    pieces1: "8 pieces",
    price1: "18",
    desc: "",
    image: "https://i.ibb.co/5B5Dm9P/Ebi-Shrimp.jpg",
  },
  {
    name: "Hamachi",
    ingredient: "Sériole",
    pieces: "4 pieces",
    price: "17",
    pieces1: "8 pieces",
    price1: "28",
    desc: "",
    image: "",
  },
  {
    name: "Salmon",
    ingredient: "Saumon",
    pieces: "4 pieces",
    price: "15",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "",
  },
  {
    name: "Scallop",
    ingredient: "Saint-Jacques",
    pieces: "4 pieces",
    price: "16",
    pieces1: "8 pieces",
    price1: "26",
    desc: "",
    image: "",
  },
  {
    name: "Tuna",
    ingredient: "Thon",
    pieces: "4 pieces",
    price: "15",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "",
  },
  {
    name: "Kani Crabe Stick",
    ingredient: "Bâtonnets de /Crabe",
    pieces: "4 pieces",
    price: "14",
    pieces1: "8 pieces",
    price1: "21",
    desc: "",
    image: "",
  },
  {
    name: "Unagi Eel",
    ingredient: "Anguille",
    pieces: "4 pieces",
    price: "17",
    pieces1: "8 pieces",
    price1: "28",
    desc: "",
    image: "",
  },
];
export const palaisSushiChefSignaturesRolls = [
  {
    name: "Alaskan Salmon",
    ingredient:
      "Saumon Frais, Avocat, Concombre, Mayonnaise Japonaise Epicée Croquant, Nori, Riz",
    pieces: "4 pieces",
    price: "10",
    pieces1: "8 pieces",
    price1: "18",
    desc: "",
    image: "https://i.ibb.co/0sy9kF8/Alaskan-Salmon.jpg",
  },
  {
    name: "Angry Crab",
    ingredient:
      "Kani Crabe, Thon, Avocat, Mayonnaise Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "12",
    pieces1: "8 pieces",
    price1: "22",
    desc: "",
    image: "",
  },
  {
    name: "Boston",
    ingredient: "Saumon et Thon Frais, Oignon Vert, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "14",
    pieces1: "8 pieces",
    price1: "26",
    desc: "",
    image: "",
  },
  {
    name: "Crunchy Honey Prawn",
    ingredient:
      "Crevetes Japonaises, Kani Crabe Avocat, Sauce Au miel, Croquant, Mayonnaise Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "11.5",
    pieces1: "8 pieces",
    price1: "21",
    desc: "",
    image: "",
  },
  {
    name: "Happy Prawns",
    ingredient:
      "Crevette Japonaise, Mayonnaise Japonaise Epicée, Concombre, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "10.5",
    pieces1: "8 pieces",
    price1: "19",
    desc: "",
    image: "",
  },
  {
    name: "King Crunchy",
    ingredient:
      "Kani Crabe, Avocatm Concombre, Crunchy Tempura, Mayonnaise Japonaise Epicée, Nori, Riz",
    pieces: "4 pieces",
    price: "9",
    pieces1: "8 pieces",
    price1: "16",
    desc: "",
    image: "",
  },
  {
    name: "Monster Roll",
    ingredient: "Crevette Tempura, Saumon Frais, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "14",
    pieces1: "8 pieces",
    price1: "26",
    desc: "",
    image: "",
  },
  {
    name: "Scallion Maguro",
    ingredient:
      "Thon, Kani Crabe, Avocat, Oignon Vert, Sauce Teriyaki, Nori, Riz",
    pieces: "4 pieces",
    price: "12",
    pieces1: "8 pieces",
    price1: "22",
    desc: "",
    image: "",
  },
  {
    name: "Tempura Shrimp",
    ingredient:
      "Crevette Tempura, Viya Crabe, Mayonnaise Japonaise Epicée, Avocat, Nori, Riz",
    pieces: "3 pieces",
    price: "11",
    pieces1: "6 pieces",
    price1: "20",
    desc: "",
    image: "",
  },
  {
    name: "Volcano",
    ingredient:
      "Saint-Jacques Grillé, Kani Crabe, Mayonnaise Japonaise Epicée, Avocat, Nori, Riz",
    pieces: "4 pieces",
    price: "14",
    pieces1: "8 pieces",
    price1: "26",
    desc: "",
    image: "",
  },
  {
    name: "Yellow Tail",
    ingredient: "Sériole, Thon, Crevettes Tempura, Piment Jalapeno, Nori, Riz",
    pieces: "4 pieces",
    price: "12.5",
    pieces1: "8 pieces",
    price1: "23",
    desc: "",
    image: "",
  },
];
export const palaisSushiLesPlateaux = [
  {
    name: "Chori (Cooked Item 16 Pcs",
    ingredient: "Volcano, King Crunchy, Osaka salmon, Chrunchy honey prawn",
    pieces: "16 pieces",
    price: "40",
    desc: "",
    image: "https://i.ibb.co/MnCdD6Q/Chori-1.jpg",
  },
  {
    name: "Fuji Mountain",
    ingredient:
      "Crunchy Crazy, Caterpillar, Nigiri Tuna Hokkigai, Nigiri Salmon, Nigiri yellowtail, Ngiri Green masago",
    pieces: "32 pieces",
    price: "65",
    desc: "",
    image: "",
  },
  {
    name: "Hiroshima",
    ingredient:
      "Hokkaide Crunchy Shrimp, California. Kaizen, Chuguko Spicy Crab & shrimp, yasai Maki, Tuna & Avocado Maki, Salmon Maki, Kani Crab Maki",
    pieces: "28 pieces",
    price: "55",
    desc: "",
    image: "",
  },
  {
    name: "Kimono",
    ingredient:
      "Nigiri Tuna, Nigiri Salmon, Nigiri ebi, Nigiri hokkigai, Nigiri Eel, Nigiri yellowtail, Nigiri green masago",
    pieces: "14 pieces",
    price: "47",
    desc: "",
    image: "",
  },
  {
    name: "Samurai",
    ingredient: "Boston, Crunchy honey Prawn Scallion Maguro, Monster",
    pieces: "16 pieces",
    price: "42",
    desc: "",
    image: "",
  },
  {
    name: "Sumo Sashimi",
    ingredient:
      "Eel, Kani Crab Stick, Ebi Shrimp, Scallop, Salmon, Tuna, Masago",
    pieces: "31 pieces",
    price: "85",
    desc: "",
    image: "",
  },
  {
    name: "Tsunami",
    ingredient:
      "Fantastic Rolls, Philly Roll, Dragon Roll, Salmon Maki Rainbow Roll",
    pieces: "38 pieces",
    price: "71",
    desc: "",
    image: "",
  },
];
// {
//   name: "",
//   ingredient: "",
//   pieces: "",
//   price: "",
//   desc: "",
//   image: "",
// },
